---
- hosts: nerdrage
  tasks:
    
    - name: Ensure root directory for NerdRage files is created on remote Docker host
      become: yes
      file:
          path: "/NerdRage"
          state: directory
          mode: 0775
          owner: ubuntu
          group: ubuntu
    
    - name: Create container network
      docker_network:
          name: nerdrage

    - name: Ensure Docker container for PlatformIO Remote is destroyed
      docker_container:
          name: nerdrage-platformio-remote
          state: absent

    - name: Ensure Docker container for PlatformIO WebApp is instantiated
      docker_container:
          name: nerdrage-webapp
          image: matthijsbos/nerdrage-webapp:latest
          state: started
          restart: yes
          restart_policy: unless-stopped
          devices:
            - "/dev/ttyUSB0:/dev/ttyUSB0"
          published_ports:
            - "80:8080"
          pull: yes
          recreate: yes

    - name: Ensure directory for Crossbar config files is created on remote Docker host
      become: yes
      file:
          path: "/NerdRage/crossbar"
          state: directory
          mode: 0775
          owner: ubuntu
          group: ubuntu

    - name: Ensure crossbar config file is copied to remote docker host file system
      copy:
          src: "./crossbar/config.json"
          dest: "/NerdRage/config.json"
          owner: ubuntu
          group: ubuntu
          mode: 0775

    - name: Ensure Docker container for CrossbarIO is instantiated
      docker_container:
          name: nerdrage-crossbar
          image: crossbario/crossbar-aarch64
          published_ports: 
            - "8080:8080"
          state: started
          restart: yes
          restart_policy: unless-stopped
          recreate: yes
          volumes:
            - "~/crossbar:/node"
          networks:
            - name: nerdrage 
              aliases:
                - nerdrage-crossbar